import { Client } from 'pg';

import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const connectionString = process.env.DATABASE_URL || 'postgresql://postgres:wtm%40212223wtm@db.aiyutkdfpadznicpvtvw.supabase.co:5432/postgres';

async function rebuildDatabase() {
    console.log(' Connecting to Supabase PostgreSQL database...');
    const client = new Client({
        connectionString,
        ssl: { rejectUnauthorized: false }
    });

    try {
        await client.connect();
        console.log(' Connected to PostgreSQL database!');

        const sql = `
        -- 1. PROFILES TABLE
        CREATE TABLE IF NOT EXISTS public.profiles (
            id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
            username TEXT UNIQUE,
            display_name TEXT,
            avatar_url TEXT,
            bio TEXT,
            is_public BOOLEAN DEFAULT true,
            show_stats_publicly BOOLEAN DEFAULT true,
            public_note TEXT,
            social_links JSONB DEFAULT '{}'::jsonb,
            top_favorites JSONB DEFAULT '[]'::jsonb,
            recent_watches JSONB DEFAULT '[]'::jsonb,
            taste_dna JSONB DEFAULT '{}'::jsonb,
            onboarding_completed BOOLEAN DEFAULT false,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        );

        -- 2. HANDLE_NEW_USER TRIGGER FUNCTION
        CREATE OR REPLACE FUNCTION public.handle_new_user()
        RETURNS TRIGGER AS $$
        BEGIN
          INSERT INTO public.profiles (id, username, display_name, avatar_url)
          VALUES (
            NEW.id,
            SPLIT_PART(NEW.email, '@', 1) || '_' || SUBSTRING(MD5(RANDOM()::text) FROM 1 FOR 4),
            SPLIT_PART(NEW.email, '@', 1),
            NEW.raw_user_meta_data->>'avatar_url'
          )
          ON CONFLICT (id) DO NOTHING;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;

        -- Trigger binding
        DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
        CREATE TRIGGER on_auth_user_created
          AFTER INSERT ON auth.users
          FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

        -- 3. USER_INTERACTIONS TABLE
        CREATE TABLE IF NOT EXISTS public.user_interactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
            movie_id BIGINT NOT NULL,
            title TEXT,
            poster_path TEXT,
            liked BOOLEAN,
            has_watched BOOLEAN DEFAULT true,
            rating NUMERIC,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW(),
            CONSTRAINT user_movie_unique UNIQUE (user_id, movie_id)
        );

        -- 4. MOVIES TABLE
        CREATE TABLE IF NOT EXISTS public.movies (
            id BIGINT PRIMARY KEY,
            title TEXT NOT NULL,
            overview TEXT,
            poster_path TEXT,
            backdrop_path TEXT,
            vote_average NUMERIC,
            release_date TEXT,
            runtime INT,
            genre TEXT,
            genres JSONB,
            custom_blurb TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        );

        -- 5. WATCHLIST TABLE
        CREATE TABLE IF NOT EXISTS public.watchlist (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
            movie_id BIGINT NOT NULL,
            title TEXT,
            poster_path TEXT,
            vote_average NUMERIC,
            release_date TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            CONSTRAINT user_watchlist_movie_unique UNIQUE (user_id, movie_id)
        );

        -- 6. INDEXES
        CREATE INDEX IF NOT EXISTS idx_user_interactions_user_id ON public.user_interactions(user_id);
        CREATE INDEX IF NOT EXISTS idx_user_interactions_movie_id ON public.user_interactions(movie_id);
        CREATE INDEX IF NOT EXISTS idx_watchlist_user_id ON public.watchlist(user_id);
        CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles(username);

        -- 7. ROW LEVEL SECURITY (RLS) POLICIES
        ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.user_interactions ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.movies ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;

        -- Profiles RLS policies
        DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
        CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);

        DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
        CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

        DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
        CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

        -- User Interactions RLS policies
        DROP POLICY IF EXISTS "User interactions are viewable by everyone" ON public.user_interactions;
        CREATE POLICY "User interactions are viewable by everyone" ON public.user_interactions FOR SELECT USING (true);

        DROP POLICY IF EXISTS "Users can insert their own interactions" ON public.user_interactions;
        CREATE POLICY "Users can insert their own interactions" ON public.user_interactions FOR INSERT WITH CHECK (auth.uid() = user_id);

        DROP POLICY IF EXISTS "Users can update their own interactions" ON public.user_interactions;
        CREATE POLICY "Users can update their own interactions" ON public.user_interactions FOR UPDATE USING (auth.uid() = user_id);

        DROP POLICY IF EXISTS "Users can delete their own interactions" ON public.user_interactions;
        CREATE POLICY "Users can delete their own interactions" ON public.user_interactions FOR DELETE USING (auth.uid() = user_id);

        -- Movies RLS policies
        DROP POLICY IF EXISTS "Movies are viewable by everyone" ON public.movies;
        CREATE POLICY "Movies are viewable by everyone" ON public.movies FOR SELECT USING (true);

        DROP POLICY IF EXISTS "Anyone can insert movies" ON public.movies;
        CREATE POLICY "Anyone can insert movies" ON public.movies FOR INSERT WITH CHECK (true);

        DROP POLICY IF EXISTS "Anyone can update movies" ON public.movies;
        CREATE POLICY "Anyone can update movies" ON public.movies FOR UPDATE USING (true);

        -- Watchlist RLS policies
        DROP POLICY IF EXISTS "Users can view their own watchlist" ON public.watchlist;
        CREATE POLICY "Users can view their own watchlist" ON public.watchlist FOR SELECT USING (auth.uid() = user_id);

        DROP POLICY IF EXISTS "Users can insert into their own watchlist" ON public.watchlist;
        CREATE POLICY "Users can insert into their own watchlist" ON public.watchlist FOR INSERT WITH CHECK (auth.uid() = user_id);

        DROP POLICY IF EXISTS "Users can delete from their own watchlist" ON public.watchlist;
        CREATE POLICY "Users can delete from their own watchlist" ON public.watchlist FOR DELETE USING (auth.uid() = user_id);
        `;

        await client.query(sql);
        console.log(' Database schema successfully rebuilt and configured!');

    } catch (err: any) {
        console.error(' Database Rebuild Error:', err);
    } finally {
        await client.end();
    }
}

rebuildDatabase();
